kind: pipeline
type: kubernetes
name: golang-app
steps:
  - name: test
    image: golang:alpine
    commands:
      - "go test"
  - name: build
    image: golang:alpine
    commands:
      - "go build -o ./myapp"
  - name: publish
    image: plugins/docker
    settings:
      repo: magalixcorp/k8scicd
      tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: deliver
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl apply -f deployment.yml

---
kind: pipeline
type: kubernetes
name: greeting

steps:
  - name: en
    image: alpine
    commands:
      - echo hello world

  - name: fr
    image: alpine
    commands:
      - echo bonjour monde

---
kind: pipeline
type: kubernetes
name: fr

steps:
  - name: greeting
    image: alpine
    commands:
      - echo next steps
